"""Lesson23 unet"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/06_preprocessing.lesson_23.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/06_preprocessing.lesson_23.ipynb 3
from cv_tools.core import *


# %% ../../nbs/06_preprocessing.lesson_23.ipynb 4
import shutil,timm,os,torch,random,datasets,math
import fastcore.all as fc, numpy as np, matplotlib as mpl, matplotlib.pyplot as plt
#import k_diffusion as K, torchvision.transforms as T
import torchvision.transforms.functional as TF,torch.nn.functional as F

from torch.utils.data import DataLoader,default_collate
from pathlib import Path
from torch.nn import init
from fastcore.foundation import L
from torch import nn,tensor
from operator import itemgetter
from torcheval.metrics import MulticlassAccuracy
from functools import partial
from torch.optim import lr_scheduler
from torch import optim
from torchvision.io import read_image,ImageReadMode
from glob import glob

from miniai.datasets import *
from miniai.conv import *
from miniai.learner import *
from miniai.activations import *
from miniai.init import *
from miniai.sgd import *
from miniai.resnet import *
from miniai.augment import *
from miniai.accel import *
from miniai.training import *
